<a href="https://colab.research.google.com/github/AmanKh9153/Assignment1_solution/blob/main/Assignment2_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Importing Necessary Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
%matplotlib inline

In [ ]:
!pip3 install openpyxl

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#### Loading the Dataset to a Dataframe

In [ ]:
root_folder = '/content/drive/MyDrive/DS503Assignment1_11841160_11841200/Q2/CCPP' #set path accordingly
mydf = pd.read_excel(root_folder+'/Folds5x2_pp.xlsx',engine='openpyxl')
mydf

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [ ]:
## Dropping any duplicate rows if present
mydf.drop_duplicates(keep='first',ignore_index=True)
mydf

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

#### Loading the Independent Variables

In [ ]:
X=mydf[['AT','V','AP','RH']].to_numpy()
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

#### Standardizing the Data

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=scaler.fit_transform(X)
X

array([[-0.62951938, -0.98729659,  1.8204884 , -0.00951935],
       [ 0.74190911,  0.68104512,  1.1418628 , -0.97462052],
       [-1.95129733, -1.17301765, -0.18507756,  1.2898397 ],
       ...,
       [ 1.56583973,  1.57581141, -0.05709854, -2.52261812],
       [ 0.64797565,  1.19177803,  0.1011913 , -0.74790051],
       [ 0.26150656,  0.64641916,  0.66867722, -0.37254534]])

In [ ]:
### We first need to add a column of 1s to X for the bias/intercept term
x_new = np.append(np.ones((X.shape[0],1)),X,axis=1)
print(x_new)

[[ 1.         -0.62951938 -0.98729659  1.8204884  -0.00951935]
 [ 1.          0.74190911  0.68104512  1.1418628  -0.97462052]
 [ 1.         -1.95129733 -1.17301765 -0.18507756  1.2898397 ]
 ...
 [ 1.          1.56583973  1.57581141 -0.05709854 -2.52261812]
 [ 1.          0.64797565  1.19177803  0.1011913  -0.74790051]
 [ 1.          0.26150656  0.64641916  0.66867722 -0.37254534]]


#### Defining the dependent variable

In [ ]:
y=mydf['PE'].to_numpy()

### Normal Equations Method

In [ ]:
# Using Normal Equation.
start = time.process_time() 
theta_best_values=np.linalg.inv(x_new.T.dot(x_new)).dot(x_new.T).dot(y)
print("The weights obtained by normal equations method are: \n",theta_best_values)
print("The first term corresponds to the bias/intercept")
print("time taken is ",time.process_time() - start, "seconds")

The weights obtained by normal equations method are: 
 [ 4.54365009e+02 -1.47365933e+01 -2.97242952e+00  3.68677907e-01
 -2.30751179e+00]
The first term corresponds to the bias/intercept
time taken is  0.005769886999999585 seconds


In [ ]:
## The predicted values for each data point using the normal equations method are as follows
predicted_values=x_new.dot(theta_best_values)
print(predicted_values)

[467.26978996 444.0773659  483.56264263 ... 432.40579787 443.03667582
 449.69603741]


In [ ]:
## The mean square error is as follows using the normal equations method
mse = ((predicted_values - y)**2).mean(axis=0)
print("Mean Square Error",mse)

Mean Square Error 20.767397532535025


In [ ]:
## The sum of least squared error
print("The sum of least square error is",mse*9568)

The sum of least square error is 198702.4595912951


#### Next we find the top 5 data points with the maximum mean square error

In [ ]:
mse_per_point = ((predicted_values - y)**2)
mse_per_point.shape

(9568,)

In [ ]:
a=np.array([1,2,3,4,5])
a.argsort()[-3:]

array([2, 3, 4])

In [ ]:
## Getting the indices of data points with maximum error
maxerror5_index=mse_per_point.argsort()[-5:][::-1]
maxerror5_index

array([3117, 7664, 3383, 7398, 3895])

In [ ]:
## The values of maximum least squared errors are
mse_per_point[maxerror5_index]

array([1886.63342877, 1852.08383355, 1471.24994754,  965.66152175,
        961.64822569])

In [ ]:
## Printing the data points
mydf.iloc[maxerror5_index]

AT      V       AP     RH      PE
3117   8.74  36.30  1015.18  61.97  438.63
7664   7.14  41.22  1016.60  97.09  435.58
3383   6.22  39.85  1012.05  86.88  443.73
7398   7.06  41.74  1021.95  90.38  448.97
3895  14.69  49.64  1023.43  78.17  434.12

In [ ]:
### Printing min,max,avg for each Independent Variable
temp=pd.DataFrame(columns=mydf.columns)
print("minimum\n",pd.DataFrame(mydf.min()).transpose())
print("maximum\n",pd.DataFrame(mydf.max()).transpose())
print("average\n",pd.DataFrame(mydf.mean()).transpose())

minimum
      AT      V      AP     RH      PE
0  1.81  25.36  992.89  25.56  420.26
maximum
       AT      V      AP      RH      PE
0  37.11  81.56  1033.3  100.16  495.76
average
           AT          V           AP         RH          PE
0  19.651231  54.305804  1013.259078  73.308978  454.365009


#### Check if the 5 data points with maximum error are outliers

In [ ]:
from numpy.random import seed
from numpy.random import randn
from numpy import percentile
## Helper function to check if a data point is outlier using interquartile range method
def check_outlier(x):
    mydic={}
    for col_name in ['AT','V','AP','RH']:
        q25, q75 = percentile(mydf[col_name].to_numpy(), 25), percentile(mydf[col_name].to_numpy(), 75)
        iqr = q75 - q25
        cut_off = iqr * 1.5
        lower, upper = q25 - cut_off, q75 + cut_off
        if x[col_name]<lower or x[col_name]>upper:
            mydic[col_name]=True
        else:
            mydic[col_name]=False
    return mydic

we can check if the data points are outliers using the interquartile range method (which specifies it with respect to each column). We observe that none of the points are outliers.

In [ ]:
## We find that none of the points are outliers with respect to each independent variable using the IQR method.
count=1
for index in maxerror5_index:
    print("data point",count,check_outlier(mydf.iloc[index]))
    count = count+1

data point 1 {'AT': False, 'V': False, 'AP': False, 'RH': False}
data point 2 {'AT': False, 'V': False, 'AP': False, 'RH': False}
data point 3 {'AT': False, 'V': False, 'AP': False, 'RH': False}
data point 4 {'AT': False, 'V': False, 'AP': False, 'RH': False}
data point 5 {'AT': False, 'V': False, 'AP': False, 'RH': False}


### QR Decomposition Method

In [ ]:
start=time.process_time()
Q, R = np.linalg.qr(x_new)
b = np.linalg.inv(R).dot(Q.T).dot(y)
print("The weights obtained by QR decomposition method are: \n",b)
print("The first term corresponds to the bias/intercept")
print("time taken is ",time.process_time() - start, "seconds")

The weights obtained by QR decomposition method are: 
 [ 4.54365009e+02 -1.47365933e+01 -2.97242952e+00  3.68677907e-01
 -2.30751179e+00]
The first term corresponds to the bias/intercept
time taken is  0.010310193999998774 seconds


In [ ]:
## Predict using QR decomposition Method
yhat = x_new.dot(b)

In [ ]:
## The mean square error is as follows using the normal equations method
mse = ((predicted_values - y)**2).mean(axis=0)
print("Mean Square Error",mse)

Mean Square Error 20.767397532535025


In [ ]:
## The sum of least squared error
print("The sum of least square error is",mse*9568)

The sum of least square error is 198702.4595912951


#### Next we find the top 5 data points with the maximum mean square error

In [ ]:
mse_per_point = ((predicted_values - y)**2)
mse_per_point.shape

(9568,)

In [ ]:
## Getting the indices of data points with maximum error
maxerror5_index=mse_per_point.argsort()[-5:][::-1]
maxerror5_index

array([3117, 7664, 3383, 7398, 3895])

In [ ]:
## Printing the data points
mydf.iloc[maxerror5_index]

AT      V       AP     RH      PE
3117   8.74  36.30  1015.18  61.97  438.63
7664   7.14  41.22  1016.60  97.09  435.58
3383   6.22  39.85  1012.05  86.88  443.73
7398   7.06  41.74  1021.95  90.38  448.97
3895  14.69  49.64  1023.43  78.17  434.12

We observe that these points remain unchanged because the coefficient matrix obtained for QR factorization method is the same as normal equations method in this example.

### Randomized SVD Method

In [ ]:
# Randomized SVD using pseudo inverse
start=time.process_time()
b = np.linalg.pinv(x_new).dot(y)
print("The weights obtained by QR decomposition method are: \n",b)
print("The first term corresponds to the bias/intercept")
print("time taken is ",time.process_time() - start, "seconds")

The weights obtained by QR decomposition method are: 
 [ 4.54365009e+02 -1.47365933e+01 -2.97242952e+00  3.68677907e-01
 -2.30751179e+00]
The first term corresponds to the bias/intercept
time taken is  0.008457807999995737 seconds


In [ ]:
predicted_svd=x_new.dot(b)

In [ ]:
### Printing the mean square error
mse_svd = ((predicted_svd - y)**2).mean(axis=0)
mse_svd

20.767397532535004

In [ ]:
## The sum of least squared error
print("The sum of least square error is",mse_svd*9568)

The sum of least square error is 198702.4595912949


Next we find the top 5 datapoints with maximum error

In [ ]:
mse_per_point_svd = ((predicted_svd - y)**2)
mse_per_point_svd.shape

(9568,)

In [ ]:
maxerror5_index=mse_per_point_svd.argsort()[-5:][::-1]
maxerror5_index

array([3117, 7664, 3383, 7398, 3895])

In [ ]:
## Printing the data points
mydf.iloc[maxerror5_index]

AT      V       AP     RH      PE
3117   8.74  36.30  1015.18  61.97  438.63
7664   7.14  41.22  1016.60  97.09  435.58
3383   6.22  39.85  1012.05  86.88  443.73
7398   7.06  41.74  1021.95  90.38  448.97
3895  14.69  49.64  1023.43  78.17  434.12

### Observations

We observe that the weight coefficients and bias term are exactly the same in all three methods. Hence the predictions and points with maximum error are also the same. However the time taken to compute the weight coefficients is different. We find  time(Normal Equations)< time(Randomized SVD) < time(QR decomposition).
Another observation is that none of the data points with maximum error are found to be outliers using the Inter Quartile Range method.

### Verifying results using Linear Regression with Gradient Descent from sklearn

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)

In [ ]:
print(reg.coef_)
print(reg.intercept_)

[-14.73659333  -2.97242952   0.36867791  -2.30751179]
454.36500940635455
